###
GET http://127.0.0.1:3000/order/?spotID=25 HTTP/1.1
###
POST http://127.0.0.1:3000/order/create HTTP/1.1
Content-Type: application/json

{
    "packageID": "{{$randomInt 1 100}}",
    "receive_point_id": "{{$randomInt 1 50}}",
    "send_point_id": "{{$randomInt 51 100}}",
    "status": "on delivery",
    "address_receive": "Hanoi",
    "address_sent": "Hanoi",
    "type": "spot" 
}
###
POST http://127.0.0.1:3000/order/create
Content-Type: application/json

{
    "packageID": "433143314",
    "receiveAreaID": "nam_tu_liem",
    "sendAreaID": "nam_tu_liem",
    "type": "to transaction spot",
    "status": "on delivery",
    "address_receive": "Hanoi",
    "address_send": "Hanoi",
    "sendDate": "2023-01-03"
}
###
GET http://127.0.0.1:3000/order/confirm/85115 HTTP/1.1
###
POST http://127.0.0.1:3000/track/ HTTP/1.1
Content-Type: application/json

{
    "packageID": "1000"
}
###
POST http://127.0.0.1:3000/package/create HTTP/1.1
Content-Type: application/json

{
    "packageID": "{{$randomInt 1 100}}",
    "receivePointID": "{{$randomInt 1 50}}",
    "sendPointID": "{{$randomInt 51 100}}",
    "status": "on delivery",
    "sender": {
        "province": "Hà Nội",
        "district": "Bắc Từ Liêm"
    },
    "recipient": {
        "province": "Hà Nội",
        "district": "Bắc Từ Liêm"
    },
    "cost": "{{$randomInt 1 1000000}}"
}
###
POST http://127.0.0.1:3000/package/ HTTP/1.1
Content-Type: application/json

{

}
###
POST http://127.0.0.1:3000/package/update HTTP/1.1
Content-Type: application/json

{
    "packageID": "89",
    "receivePointID": "1",
    "sendPointID": "2"
}
###
GET http://127.0.0.1:3000/province
###
GET http://127.0.0.1:3000/district?province=Hà%20Nội
###
GET http://127.0.0.1:3000/transactionPoint/order?type=pending
###
GET http://127.0.0.1:3000/package/statistic
###
GET http://127.0.0.1:3000/package/statistic?spotID=2
### 
GET http://127.0.0.1:3000/warehouse/1/statistics
###
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "employeeTransaction",
    "password": "123456"
}
###
GET http://127.0.0.1:3000/manager/statistic?pointID=658a5655cb954fd8511ef8b8
###
GET http://127.0.0.1:3000/transactionPoint/order?type=pending&pointID=658dace90fc0efb969007e0c
### 
GET http://127.0.0.1:3000/transactionPoint/order/create?type=toCustomer&packageID=420233557&pointID=658dd07c373d3ae33ac5d480
###
GET http://127.0.0.1:3000/warehouse/order?pointID=658a5655cb954fd8511ef8b8 HTTP/1.1
###
GET http://127.0.0.1:3000/warehouse/package?pointID=658a5655cb954fd8511ef8b8&type=pending HTTP/1.1
###
GET http://127.0.0.1:3000/transactionPoint/package?pointID=658dd07c373d3ae33ac5d480 HTTP/1.1

###